version: '3.8'
services:
  postgres:
    image: bitnami/postgresql:15
    ports:
      - 5432:5432
    volumes:
      - postgres:/bitnami/postgresql
    environment:
      ALLOW_EMPTY_PASSWORD: 'yes'
volumes:
  postgres: null
